root = "."
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "docker-compose up --build"
  delay = 2000
  exclude_dir = [
    "tmp",
    "testdata",
    "output",
    "internal/textproc/testdata/",
    "internal/cmd/testtmp",
    "testtmp",
    ]
  exclude_file = []
  exclude_regex = [
    "_test\\.go$",
    "testdata/testtmp[0-9]+$\\",
    "cmd/testtmp[0-9]+$",
    "out[0-9]+.txt$",
    "internal/textproc/testdata/testtmp[0-9]+$",
    "$(pwd)/internal/textproc/testdata/testtmp[0-9]+$",
    "internal/textproc/testdata/testtmp[0-9]+/out[0-9]+\\.txt$",
    "testdata/testtmp[0-9]+$",
    "testdata/*.txt"
  ]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "500"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = true
  time = true

[misc]
  clean_on_exit = true

[proxy]
  enabled = false
  app_port = 0
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
