services:
  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
        restart: true
      migrate:
        condition: service_completed_successfully
    env_file:
      - .env
    networks:
      db_network:
    ports:
      - 80:8080
    volumes:
      - ./output:/output
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:?database user not set}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?database password not set}
      POSTGRES_DB: ${DB_NAME:?database name not set}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
      - 8080:8080
    env_file:
      - .env
    networks:
      db_network:


  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/db/migrations
    command: [ "-path", "/db/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable", "up" ]
    networks:
      db_network:


volumes:
  postgres_data:


networks:
  db_network:
