services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        restart: true
      migrate:
        condition: service_completed_successfully
    networks:
      db_network:
    volumes:
      - ./output:/output
    ports:
      - "8080:8080"

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 1s
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      db_network:
    env_file:
      - .env


  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/db/migrations
    command: [
      "-path",
      "/db/migrations",
      "-database",
      "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable",
      "up",
       ]
    networks:
      db_network:


volumes:
  postgres_data:


networks:
  db_network:
